name: cm-poverty-mapping
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - geopandas
  - rasterio
  - pandas
  - numpy
  - scikit-learn
  - lightgbm
  - shap
  - folium
  - pyyaml
  - tqdm
  - pip
  - pip:
      - earthengine-api
      - leafmap